DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dest INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT (datetime('now','localtime')),
  body TEXT NOT NULL,
  FOREIGN KEY (dest) REFERENCES user (id)
);